version: "3.8"
services:
  postgres:
    image: aidemo-postgres # this names the image we create in ./docker/postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust # Not recommended! But c'mon, it's fine for single-user local dev. https://www.postgresql.org/docs/current/auth-trust.htm
    volumes:
      - $HOME/.aidemo/database:/var/lib/postgresql/data
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
      args:
        - VERSION=14-3.2
